print("Nome")
nome = input("Digite o seu nome: ")
print("Endereço")
rua = input("Digite o nome da rua: ")
cep = int(input("Digite o número do CEP: "))
bairro = input("Digite o nome do bairro: ")
estado = input("Digite o nome do estado: ")
print("Telefone")
tel = int(input("Digite o número do telefone: "))

arq = open("cadastro.txt", "a")
arq.write("Nome:")
arq.write("\n")
arq.write(nome)
arq.write("\n")
arq.write("Endereço:")
arq.write("\n")
arq.write("Rua: ")
arq.write(rua)
arq.write("\n")
arq.write("CEP: ")
arq.write(str(cep))
arq.write("\n")
arq.write("Bairro: ")
arq.write(bairro)
arq.write("\n")
arq.write("Estado: ")
arq.write(estado)
arq.write("\n")
arq.write("Telefone: ")
arq.write(str(tel))
arq.write("\n")
arq.write("\n")
arq.close()